# Template credit: https://github.com/sveltejs/kit/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
name: "\U0001F41E Bug report"
description: Report an issue with Wordchain
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: "Steps to reproduce the behavior:"
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "If there are any relavent errors in the console, please put them here."
      render: Shell
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please include the device and browser this issue was found on.
      render: Shell
      placeholder: Device, Browser
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
